/* eslint-disable object-curly-newline */
/* eslint-disable quotes */
const cocktails = [
  { name: "Dark and Stormy", directions: "Dark and Stormy\r\n\r\nIngredients:\r\n2 oz  dark rum\r\n1/2 oz  lime juice (optional)\r\n3 oz  Ginger beer\r\n\r\nInstructions:\r\nFill tall glass with ice and rum. Pour in ginger beer and lime.\r\nStir and garnish with a lime wedge.\r\n\r\nGlassServe: Highball glass", cId: "999999999", img: "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/lede-1550781637.png", genre: "latin" },
  { name: "Gin & Tonic", directions: "Gin & Tonic\r\n\r\nIngredients:\r\n1 1/2 oz  Gin\r\n1 lemon and/or lime wedge\r\nTop up with tonic\r\n\r\nInstructions:\r\nAdd the gin to a highball glass and fill with fresh ice.\r\nTop up with tonic water.\r\nSqueeze the citrus into the drink, drop into the glass and stir.\r\n\r\nGlassServe: Highball glass", img: "https://cdn.liquor.com/wp-content/uploads/2016/08/10113036/gin-and-tonic-720x720-article.jpg", cId: "999999998", genre: "classical" },
  { name: "Sea breeze", directions: "Sea breeze\r\n\r\nIngredients:\r\n1 1/2 oz  Vodka\r\n4 oz  Cranberry juice\r\n1 oz  Grapefruit juice\r\n\r\nInstructions:\r\nBuild all ingredients in a highball glass filled with ice.\r\nGarnish with lime wedge.\r\n\r\nGlassServe: Highball glass", img: "https://www.thecocktaildb.com/images/media/drink/7rfuks1504371562.jpg", cId: "13377", genre: "pop" },
  { name: "Just Wanna Dance", directions: "Just Wanna Dance\r\n\r\nIngredients:\r\n1 can  red bull\r\n2 oz  vodka\r\n\r\nInstructions:\r\nAdd all of the ingredients over ice and stir.\r\nOption to use less Red Bull or more Vodka.\r\n\r\nGlassServe: Highball glass", img: "https://cdn.liquor.com/wp-content/uploads/2016/12/22114511/vodka-red-bull-720x720-recipe.jpg", cId: "999999997", genre: "electro" },
  { name: "Cucumber Vodka Soda", directions: "Cucumber Vodka Soda\r\n\r\nIngredients:\r\n1 squeeze of lemon\r\n2 oz  vodka\r\nTop up with club soda\r\n\r\nInstructions:\r\nAdd all of the ingredients over ice and stir.\r\nOption to use less Red Bull or more Vodka.\r\n\r\nGlassServe: Highball glass", img: "https://cdn.liquor.com/wp-content/uploads/2016/08/18132953/vodka-soda-720x720-recipe.jpg", cId: "999999996", genre: "dance" },
  { name: "Bend's Brew", directions: "Bend's Brew\r\n\r\nIngredients:\r\n1 can  Pacific Northwest's finest IPA beer\r\n\r\nInstructions:\r\nOpen can of beer. Drink the beer and smell those piney hops.\r\n\r\nGlassServe: Can", img: "https://d1ynl4hb5mx7r8.cloudfront.net/wp-content/uploads/2018/12/17161145/Deschutes_Twitter-Image-768x402.jpg", cId: "999999995", genre: "folk" },
  { name: "GWARBar Special", directions: "GWARBar Special\r\n\r\nIngredients:\r\n1 can  Pabst Blue Ribbon\r\n1 1/2 oz  whiskey (not optional)\r\n\r\nInstructions:\r\nOpen the beer. Shoot the whiskey. Drink the beer.\r\nGarnish with more beer.\r\n\r\nGlassServe: Can and Shot glass", img: "https://assets3.thrillist.com/v1/image/1223668/size/tl-horizontal_main.jpg", cId: "999999994", genre: "metal" },
  { name: "Syd and Nancy", directions: "Syd and Nancy\r\n\r\nIngredients:\r\n1 can  Pabst Blue Ribbon\r\n1 1/2 oz  whiskey (not optional)\r\n\r\nInstructions:\r\nOpen the beer. Shoot the whiskey. Drink the beer.\r\nGarnish with more beer.\r\n\r\nGlassServe: Can and Shot glass", img: "https://assets3.thrillist.com/v1/image/1223668/size/tl-horizontal_main.jpg", cId: "999999993", genre: "punk" },
  { name: "The Blue Collar", directions: "The Blue Collar\r\n\r\nIngredients:\r\n1 can  Pabst Blue Ribbon\r\n1 1/2 oz  whiskey (not optional)\r\n\r\nInstructions:\r\nOpen the beer. Shoot the whiskey. Drink the beer.\r\nGarnish with more beer.\r\n\r\nGlassServe: Can and Shot glass", img: "https://assets3.thrillist.com/v1/image/1223668/size/tl-horizontal_main.jpg", cId: "999999992", genre: "rock" },
  { name: "The Hard Ass", directions: "The Hard Ass\r\n\r\nIngredients:\r\n2 oz  Vodka\r\n3 oz  Ginger beer\r\n1 oz  lime juice\r\n\r\nInstructions:\r\nAdd all the ingredients to a highball glass filled with ice.\r\nGarnish with a lime or two.\r\n\r\nGlassServe: Highball glass", img: "https://hgtvhome.sndimg.com/content/dam/images/hgtv/fullset/2015/6/24/1/iStock_000066920517_Moscow-Mule-Cocktail-Recipe.jpg.rend.hgtvcom.616.411.suffix/1435166415325.jpeg", cId: "999999991", genre: "rock" },
  { name: "The Wranglermaker", directions: "The Wranglermaker\r\n\r\nIngredients:\r\n1 can  Coors or Bud\r\n1 1/2 oz  whiskey (not optional)\r\n\r\nInstructions:\r\nOpen the beer. Shoot the whiskey. Drink the beer.\r\nNo bull.\r\n\r\nGlassServe: Can and Shot glass", img: "https://s3-media2.fl.yelpcdn.com/bphoto/XnKAQAqzTVd1xhjU508lIg/o.jpg", cId: "999999990", genre: "country" },
  { name: "Gin and Juice", directions: "Gin and Juice\r\n\r\nIngredients:\r\n1 1/2 oz  gin\r\nJuice of your choice:\r\nRecommend: Orange or Grapefruit\r\n\r\nInstructions:\r\nAdd all of the ingredients over ice and stir.\r\nOption to use more Gin and blend juices.\r\n\r\nGlassServe: Highball glass", img: "https://cdn.liquor.com/wp-content/uploads/2017/11/06100319/gin-and-juice-720x720-recipe.jpg", cId: "999999989", genre: "hip-hop" },
  { name: "The Delta Old Fashioned", directions: "The Delta Old Fashioned\r\n\r\nIngredients:\r\n1 teaspoon simple syrup\r\n2 dashes Peychaud's bitters\r\n1 orange/lemon slice peel (may include pith)\r\n2 oz rye or bourbon whiskey\r\n\r\nInstructions:\r\nAdd all ingredients into a mixing glass, muddle and stir briefly.\r\nFill with ice and stir again.\r\nStrain into a rocks glass over ice.\r\nTwist peel over the drink to express the oil and then drop in.\r\n\r\nGlassServe: Rocks glass", img: "https://cdn.liquor.com/wp-content/uploads/2017/09/29103812/4-Rules-for-Drinking-Scotch-old-fashioned-720x720-slideshow.jpg", cId: "999999988", genre: "blues" },
  { name: "The Tennessee Whiskey", directions: "The Tennessee Whiskey\r\n\r\nIngredients:\r\n1 teaspoon simple syrup\r\n2 dashes Angostura bitters\r\n1 orange/lemon slice peel (may include pith)\r\n2 oz rye or bourbon whiskey\r\n\r\nInstructions:\r\nAdd all ingredients into a mixing glass, muddle and stir briefly.\r\nFill with ice and stir again.\r\nStrain into a rocks glass over ice.\r\nTwist peel over the drink to express the oil and then drop in.\r\n\r\nGlassServe: Rocks glass", img: "https://cdn.liquor.com/wp-content/uploads/2017/09/29103812/4-Rules-for-Drinking-Scotch-old-fashioned-720x720-slideshow.jpg", cId: "999999987", genre: "country" },
  { name: "Hennessy Sidecar", directions: "Hennessy Sidecar\r\n\r\nIngredients:\r\n1 1/2 oz  Hennessy V.S.O.P Privilège cognac\r\n1 oz  Triple Sec / GranGala\r\n3/4 oz fresh lemon juice\r\n1/4 oz simple syrup\r\n\r\nInstructions:\r\nAdd all of the ingredients to a shaker with ice and shake.\r\nStrain into an ice-filled rocks glass.\r\n\r\nGlassServe: Rocks glass", img: "https://cdn.liquor.com/wp-content/uploads/2017/06/28095828/promontory_dianna_sanders_V01.jpg", cId: "999999986", genre: "rap" },
];

module.exports = cocktails;
